### ISSUE TITLE
Every journey has its first step...

### ISSUE THREAD

**Issue by Ashapola** [Ashapola/ashapola.github.io#1]
**_TODO:_**
- [ ] _create first locall repo_
- [ ] _create ffirst repo on github_
- [ ] _make commit localy_
- [ ] _make first push from local to remote_ 
--------------------------------------------------------------------------------------------------------------------------------
- [ ] prepare main page in html/css and call it index.html
